language: node_js

node_js:
  - '0.12'

before_install:
  - npm install -g bower
  - bower install
  - npm install

branches:
  only: master

cache:
  directories:
    - node_modules/
    - app/bower_components/
